DO $$
BEGIN
	IF NOT EXISTS (
		SELECT FROM pg_catalog.pg_roles WHERE rolname = 'app'
	) THEN
		CREATE ROLE app WITH LOGIN PASSWORD 'app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
	END IF;
END
$$;

ALTER DATABASE app OWNER TO app;

REVOKE ALL ON DATABASE app FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE app TO app;

ALTER SCHEMA public OWNER TO app;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRIGGER ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO app;

ALTER ROLE app SET search_path = public;

DO $$
BEGIN
	BEGIN
		REVOKE pg_execute_server_program FROM app;
	EXCEPTION WHEN undefined_object THEN
	END;
	BEGIN
		REVOKE pg_read_server_files FROM app;
	EXCEPTION WHEN undefined_object THEN
	END;
	BEGIN
		REVOKE pg_write_server_files FROM app;
	EXCEPTION WHEN undefined_object THEN
	END;
END
$$; 