<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCK546M8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCK546M8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCK546M8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCK546M8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCK546M8\App_KernelDevDebugContainer([
    'container.build_hash' => 'CK546M8',
    'container.build_id' => '8f6e9bc8',
    'container.build_time' => 1745680644,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCK546M8');
