FROM node:18-slim

RUN apt-get update && apt-get install -y \
    cron \
    postgresql-client \
    wget ca-certificates gnupg \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    chromium \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY docker/adminbot/package*.json ./
RUN npm install --production

COPY docker/adminbot/ .

ENTRYPOINT ["sh", "start.sh"]