version: '3.8'

services:
  php:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./:/var/www/html:rw
      - vendor_data:/var/www/html/vendor:rw
      - ./var/log:/var/www/html/var/log:rw
    ports:
      - "8055:80"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}"
    restart: unless-stopped
    mem_limit: 1g
    cpus: 1

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      
  # It is only needed to immitate the behavior of admin during CTF
  adminbot:
    build:
      context: .
      dockerfile: docker/adminbot/Dockerfile
    depends_on:
      - php
      - database
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@database:5432/${POSTGRES_DB:-app}"
      APP_URL: "http://php:80"
    restart: unless-stopped

volumes:
  database_data:
  vendor_data: